customCommands:
  - key: <c-a>
    description: Pick AI commit (copy)
    command: aicommit2 -c -y && pbpaste > .git/LAZYGIT_PENDING_COMMIT
    context: files
    subprocess: true
    showOutput: true
